import { parseStage } from '../sim/stage-parse.ts';
import type { StageDef } from '../sim/stage-parse.ts';

/** 読み込み時にすべてのステージを検証する。配置の誤りや id の重複は、起動した時点でエラーにする */
function defineStages(defs: readonly StageDef[]): readonly StageDef[] {
  const ids = new Set<string>();
  for (const def of defs) {
    parseStage(def);
    if (ids.has(def.id)) throw new Error(`stage id "${def.id}" is used more than once`);
    ids.add(def.id);
  }
  return defs;
}

/** 5 の倍数の面（節目の面）か。節目の面は、ほかの面より極端な特徴を持つ配置にする。`index` は 0 から数える */
export const isMilestoneStage = (index: number): boolean => (index + 1) % 5 === 0;

export const STAGES: readonly StageDef[] = defineStages([
  {
    id: 'warmup',
    name: 'WARMUP',
    rows: [
      '............',
      '............',
      '............',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oMooooooooMo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'ooooMooMoooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'stripes',
    name: 'STRIPES',
    rows: [
      '............',
      '............',
      '............',
      'oooooooooooo',
      '............',
      'oooooooooooo',
      '............',
      'o3o3o33o3o3o',
      '............',
      'oooooooooooo',
      '............',
      'ooMooooooMoo',
      '............',
      'oooooooooooo',
      '............',
      '3o3o3oo3o3o3',
      '............',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'checker',
    name: 'CHECKER',
    rows: [
      '............',
      '............',
      '............',
      'o.o.o.o.o.o.',
      '.2.2.2.2.2.2',
      'o.o.o.o.o.o.',
      '.o.o.o.o.o.o',
      '2.M.2.2.M.2.',
      '.o.o.o.o.o.o',
      'o.o.o.o.o.o.',
      '.2.2.2.2.2.2',
      'o.o.o.o.o.o.',
      '.o.o.o.o.o.o',
      '2.2.M.M.2.2.',
      '.o.o.o.o.o.o',
      'o.o.o.o.o.o.',
      '.2.2.2.2.2.2',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'pyramid',
    name: 'PYRAMID',
    rows: [
      '............',
      '............',
      '.....MM.....',
      '.....oo.....',
      '....oooo....',
      '....o33o....',
      '...oooooo...',
      '...o3oo3o...',
      '..oooooooo..',
      '..o3oooo3o..',
      '.oooooooooo.',
      '.o3ooMMoo3o.',
      'oooooooooooo',
      'o3oo3oo3oo3o',
      'oooooooooooo',
      '............',
      'oo.oo..oo.oo',
      'oo.oo..oo.oo',
    ],
  },
  {
    id: 'deluge',
    name: 'DELUGE',
    rows: [
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'zigzag',
    name: 'ZIGZAG',
    rows: [
      '............',
      '............',
      '............',
      'o....oo....o',
      'oo..oooo..oo',
      '.oooo..oooo.',
      '..oo....oo..',
      '............',
      '4....44....4',
      '44..4444..44',
      '.4444..4444.',
      '..44....44..',
      '............',
      'o....MM....o',
      'oo..oooo..oo',
      '.oooo..oooo.',
      '..oo....oo..',
      '............',
      '3....33....3',
      '33..3333..33',
      '.3333..3333.',
      '..33....33..',
      '............',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'heart',
    name: 'HEART',
    rows: [
      '............',
      '............',
      '............',
      '..44....44..',
      '.4oo4..4oo4.',
      '4oooooooooo4',
      '4ooooMMoooo4',
      '4oooooooooo4',
      '.4oooooooo4.',
      '..4oooooo4..',
      '...4oooo4...',
      '....4oo4....',
      '.....44.....',
      '............',
      'o.oo.oo.oo.o',
      '.oo.oooo.oo.',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'pillars',
    name: 'PILLARS',
    rows: [
      '............',
      '............',
      '............',
      'MoooMooMoooM',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      '5oo5oooo5oo5',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'diamonds',
    name: 'DIAMONDS',
    rows: [
      '............',
      '............',
      '.o...o...o..',
      'o6o.o6o.o6o.',
      '.o...o...o..',
      '............',
      '...o...o...o',
      'o.oMo.oMo.oM',
      '...o...o...o',
      '............',
      '.o...o...o..',
      'o6o.o6o.o6o.',
      '.o...o...o..',
      '............',
      '...o...o...o',
      'o.o6o.o6o.o6',
      '...o...o...o',
      '............',
      '.o...o...o..',
      'oMo.oMo.oMo.',
      '.o...o...o..',
      '............',
      '...o...o...o',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'jackpot',
    name: 'JACKPOT',
    rows: [
      '............',
      '............',
      '............',
      '............',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'oooooooooooo',
    ],
  },
  {
    id: 'invader',
    name: 'INVADER',
    rows: [
      '............',
      '............',
      '............',
      '..o......o..',
      '...o....o...',
      '..oooooooo..',
      '.ooMooooMoo.',
      'oooooooooooo',
      'o.oooooooo.o',
      'o.o......o.o',
      '...oo..oo...',
      '............',
      '............',
      '.o.o.o.o.o.o',
      'o.o.o.o.o.o.',
      '............',
      '.555..555...',
      '.5.5..5.5...',
      '...555..555.',
      '...5.5..5.5.',
      '............',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'ladder',
    name: 'LADDER',
    rows: [
      '............',
      '............',
      '............',
      'ooX777777Xoo',
      'ooXooooooXoo',
      'ooXooooooXoo',
      'ooX777777Xoo',
      'oo.oooooo.oo',
      'ooXooooooXoo',
      'ooX777777Xoo',
      'ooXooMMooXoo',
      'ooXooooooXoo',
      'oo.777777.oo',
      'ooXooooooXoo',
      'ooXooooooXoo',
      'ooX777777Xoo',
      'ooXooooooXoo',
      'oo.oooooo.oo',
      'ooX777777Xoo',
      'ooXooooooXoo',
      'ooXooooooXoo',
      'ooX777777Xoo',
      'oo.oooooo.oo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'waves',
    name: 'WAVES',
    rows: [
      '............',
      '............',
      '............',
      'oo..oo..oo..',
      'o....oo....o',
      '..33..oo..oo',
      '.3333..oooo.',
      '33..33..oo..',
      '3....33....3',
      '..Mo..33..33',
      '.oooo..3333.',
      'oo..oo..33..',
      'o....oo....o',
      '..55..oo..oo',
      '.5555..ooMo.',
      '55..55..oo..',
      '5....55....5',
      '..oo..55..55',
      '.oooo..5555.',
      'oo..oo..55..',
      'o....oo....o',
      '..33..oo..oo',
      '.3333..oooo.',
      '33..33..oo..',
      '3....33....3',
      '..oo..33..33',
      '.oooo..3333.',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'target',
    name: 'TARGET',
    rows: [
      '............',
      '............',
      '.....oo.....',
      '...oooooo...',
      '..oo4444oo..',
      '..o44oo44o..',
      '.o44oooo44o.',
      '.o4oo66oo4o.',
      '.ooo6oo6ooo.',
      'o4o6oooo6o4o',
      'o4o6o88o6o4o',
      'o4o6o88o6o4o',
      'o4oo8MM8oo4o',
      'o4oo8MM8oo4o',
      'o4o6o88o6o4o',
      'o4o6o88o6o4o',
      'o4o6oooo6o4o',
      '.ooo6oo6ooo.',
      '.o4oo66oo4o.',
      '.o44oooo44o.',
      '..o44oo44o..',
      '..oo4444oo..',
      '...oooooo...',
      '.....oo.....',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'monolith',
    name: 'MONOLITH',
    rows: [
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      'MMMMMMMMMMMM',
      '............',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
    ],
  },
  {
    id: 'bunker',
    name: 'BUNKER',
    rows: [
      '............',
      '.XXXXXXXXXX.',
      '.XMooooooMX.',
      '.XoMooooMoX.',
      '.XooMooMooX.',
      '.XoooMMoooX.',
      '.XMMMMMMMMX.',
      '.XoooMMoooX.',
      '.XooMooMooX.',
      '.XoMooooMoX.',
      '.XMooooooMX.',
      '.XooooooooX.',
      '.XoooMMoooX.',
      '.XooMMMMooX.',
      '.XXXX..XXXX.',
      '............',
      '............',
      'o.o.o..o.o.o',
      '.o.o.oo.o.o.',
      'oooooooooooo',
    ],
  },
  {
    id: 'skull',
    name: 'SKULL',
    rows: [
      '............',
      '............',
      '............',
      '...oooooo...',
      '..oooooooo..',
      '.oooooooooo.',
      '.o88oooo88o.',
      '.o88oooo88o.',
      '.oooooooooo.',
      '..ooo55ooo..',
      '..oooooooo..',
      '...o.oo.o...',
      '............',
      'o5........5o',
      '.o5......5o.',
      '..o5....5o..',
      '...oMooMo...',
      '..o5....5o..',
      '.o5......5o.',
      'o5........5o',
      '............',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'rain',
    name: 'RAIN',
    rows: [
      '............',
      '..o.........',
      '..o......o..',
      'o.4......o..',
      'o.o...o..4..',
      '4.o...o..o..',
      'o.o.o.4..o..',
      'o.4.o.o..o.o',
      'o.o.4.o.o4.o',
      '4.o.o.o.oo.4',
      'ooo.o.4.4o.o',
      'Mo4.o.o.oo.o',
      '.48.4.oooM.o',
      '.o..o.ooo..4',
      '.o.oo.444..o',
      '.o.o8.ooo.oo',
      '.8.4..Mo8.o8',
      '...o.o.o..4.',
      '...o.o.4..o.',
      '...M.4.8..o.',
      '.....o....8.',
      '.....8......',
      '............',
      '............',
      '............',
      '............',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'castle',
    name: 'CASTLE',
    rows: [
      '............',
      '............',
      'o.o......o.o',
      'ooo......ooo',
      'o8o.o..o.o8o',
      'o8oooooooo8o',
      'o8o8o88o8o8o',
      'o8oooooooo8o',
      'o8ooMooMoo8o',
      'o8oooooooo8o',
      'o8oo6oo6oo8o',
      'o8o666666o8o',
      'o8oo....oo8o',
      'o8oo....oo8o',
      'o8oo....oo8o',
      '666666666666',
      '............',
      'oo4oooooo4oo',
      'oo4oooooo4oo',
      'oo4oooooo4oo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'labyrinth',
    name: 'LABYRINTH',
    rows: [
      'MMMMMMMMMMMM',
      '............',
      'XXXXXX.XXXXX',
      'XooooXoooooX',
      'XoXX.XXXXXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXMMMMMMXoX',
      'XoXXXXXXXXoX',
      'XooooooooooX',
      'XXXXXXXXXXXX',
    ],
  },
  {
    id: 'chevron',
    name: 'CHEVRON',
    rows: [
      '............',
      '............',
      'oo...oo...oo',
      'o...oooo...o',
      '...oooooo...',
      '..ooo..ooo..',
      '.ooo....ooo.',
      'ooo......ooo',
      'oo...88...oo',
      'o...8MM8...o',
      '...8oooo8...',
      '..8oo..oo8..',
      '.8oo....oo8.',
      '8oo......oo8',
      'oo...66...oo',
      'o...6oo6...o',
      '...6oooo6...',
      '..6oo..oo6..',
      '.6oo....oo6.',
      '6oo......oo6',
      'oo...oo...oo',
      'o...oMMo...o',
      '...oooooo...',
      '..ooo..ooo..',
      '.ooo....ooo.',
      'ooo......ooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'hourglass',
    name: 'HOURGLASS',
    rows: [
      '............',
      '............',
      '888888888888',
      '.ooMooooMoo.',
      '..oooMMooo..',
      '...oooooo...',
      '....oooo....',
      '.....MM.....',
      '.....66.....',
      '.....MM.....',
      '....oooo....',
      '...oooooo...',
      '..oooooooo..',
      '.oooooooooo.',
      '888888888888',
      '............',
      '5.5.5..5.5.5',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'lattice',
    name: 'LATTICE',
    rows: [
      '............',
      '............',
      'MoXo8XMoXo8X',
      'o8X8oXo8X8oX',
      'X.XX.XX.XX.X',
      'o8XMoXo8XMoX',
      '8oXo8X8oXo8X',
      'X.XX.XX.XX.X',
      'MoXo8XMoXo8X',
      'o8X8oXo8X8oX',
      'X.XX.XX.XX.X',
      'o8XMoXo8XMoX',
      '8oXo8X8oXo8X',
      'X.XX.XX.XX.X',
      'MoXo8XMoXo8X',
      'o8X8oXo8X8oX',
      'X.XX.XX.XX.X',
      'o8XMoXo8XMoX',
      '8oXo8X8oXo8X',
      'X.XX.XX.XX.X',
      'MoXo8XMoXo8X',
      'o8X8oXo8X8oX',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'totem',
    name: 'TOTEM',
    rows: [
      '............',
      '............',
      '....8888....',
      '...o8MM8o...',
      '....8888....',
      '..oooooooo..',
      'oo.o5oo5o.oo',
      '..o5oooo5o..',
      '....oooo....',
      '...7o77o7...',
      'o..777777..o',
      '.o.o7MM7o.o.',
      '..o777777o..',
      '...7o77o7...',
      '....oooo....',
      '...o5oo5o...',
      'oo.5oooo5.oo',
      '...o5oo5o...',
      '....oooo....',
      '.....MM.....',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'starfield',
    name: 'STARFIELD',
    rows: [
      'M.o.........',
      '.........M.M',
      '............',
      '.o..........',
      '.......o....',
      '............',
      '............',
      '.M........o.',
      '..M......o..',
      '.....oM.....',
      '.........M.o',
      'o...........',
      '....o..M....',
      '..........M.',
      '....M.......',
      '.....M.o....',
      '.o..........',
      'M...........',
      '......o.....',
      '............',
      '.M.o........',
      '..o.........',
      '...o..M.....',
      '.......M....',
      '...o......oM',
      '............',
      '...o.o......',
      '.........o..',
      'o..o........',
      '..M......M..',
    ],
  },
  {
    id: 'brickwork',
    name: 'BRICKWORK',
    rows: [
      '............',
      '............',
      '............',
      'ooo.444.oMo.',
      'ooo.444.ooo.',
      '............',
      '4.oMo.777.oo',
      '4.ooo.777.oo',
      '............',
      'oMo.777.ooo.',
      'ooo.777.ooo.',
      '............',
      '7.ooo.ooo.44',
      '7.ooo.ooo.44',
      '............',
      'ooo.ooo.444.',
      'ooo.ooo.444.',
      '............',
      'o.444.oMo.77',
      'o.444.ooo.77',
      '............',
      '444.oMo.777.',
      '444.ooo.777.',
      '............',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'rocket',
    name: 'ROCKET',
    rows: [
      '............',
      '.....77.....',
      '....7777....',
      '....oooo....',
      '...oooooo...',
      '...oMooMo...',
      '...oooooo...',
      '...o5oo5o...',
      '...oooooo...',
      '...o5oo5o...',
      '...oooooo...',
      '..5oooooo5..',
      '.55oooooo55.',
      '555oooooo555',
      '55.888888.55',
      '....MMMM....',
      '....oooo....',
      '.....oo.....',
      '............',
      '............',
      'o..........o',
      '.o.o....o.o.',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'stairs',
    name: 'STAIRS',
    rows: [
      '............',
      '............',
      '7...........',
      '5...........',
      'o7..........',
      'o5..........',
      'oo7.........',
      'Mo5.........',
      'ooo7........',
      'ooo5........',
      'oooo7.......',
      'oooo5.......',
      'ooooo7......',
      'Moooo5......',
      'oooooo7.....',
      'oooooo5.....',
      'ooooooo7....',
      'ooooooo5....',
      'oooooooo7...',
      'Mooooooo5...',
      'ooooooooo7..',
      'ooooooooo5..',
      'oooooooooo7.',
      'oooooooooo5.',
      'ooooooooooo7',
      'Moooooooooo5',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'crossfire',
    name: 'CROSSFIRE',
    rows: [
      '............',
      '............',
      '7oo4oo4oo4o7',
      '774oo4oo4o77',
      '77oo4oo4oo77',
      '4774oo4oo77o',
      'o77oo4oo4774',
      'o4774oo4774o',
      '4o77oo4o77oo',
      'oo4774o77oo4',
      'o4o77oo77o4o',
      '4oo47777o4oo',
      'oo4oMMMM4oo4',
      'o4oo4MM4oo4o',
      '4oo4oMMoo4oo',
      'oo4oMMMM4oo4',
      'o4oo7777oo4o',
      '4oo77o4774oo',
      'oo4774o77oo4',
      'o4774oo4774o',
      '4o77oo4o77oo',
      'o77oo4oo4774',
      'o77o4oo4o77o',
      '77o4oo4oo477',
      '774oo4oo4o77',
      '74oo4oo4oo47',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'shafts',
    name: 'SHAFTS',
    rows: [
      '............',
      '............',
      '............',
      'MMXMMXXMMXMM',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'MMXMMXXMMXMM',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'MMXMMXXMMXMM',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'ooXooXXooXoo',
      'MMXMMXXMMXMM',
      'ooXooXXooXoo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'mushroom',
    name: 'MUSHROOM',
    rows: [
      '............',
      '............',
      '...777777...',
      '..7oooooo7..',
      '.7oMooooMo7.',
      '7oooooooooo7',
      '7oo77oo77oo7',
      '7oo77MM77oo7',
      '7oooooooooo7',
      '777777777777',
      '...oooooo...',
      '...o4oo4o...',
      '...o4oo4o...',
      '...oooooo...',
      '...o4oo4o...',
      '..oooooooo..',
      '............',
      'o.o.o..o.o.o',
      '............',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'sandwich',
    name: 'SANDWICH',
    rows: [
      '............',
      '............',
      '777777777777',
      '777777777777',
      'ooMooooooMoo',
      'ooMooooooMoo',
      'ooMooooooMoo',
      '555555555555',
      '555555555555',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      '888888888888',
      '888888888888',
      'oMooooooooMo',
      'oMooooooooMo',
      'oMooooooooMo',
      '555555555555',
      '555555555555',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'twins',
    name: 'TWINS',
    rows: [
      '............',
      '.777....777.',
      '.7M7....7M7.',
      '.7o7....7o7.',
      '.7o7....7o7.',
      '.7o7....7o7.',
      '.757....757.',
      '.7o7....7o7.',
      '.7o7....7o7.',
      '.7o7....7o7.',
      '.757....757.',
      '.7o7....7o7.',
      '.7o7....7o7.',
      '.7M7....7M7.',
      '.777....777.',
      'oooooooooooo',
      '............',
      'o.oo.oo.oo.o',
      'o.oo.oo.oo.o',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'ghost',
    name: 'GHOST',
    rows: [
      '............',
      '............',
      '............',
      '....oooo....',
      '..oooooooo..',
      '.oooooooooo.',
      '.o66oooo66o.',
      'o6MM6oo6MM6o',
      'o6MM6oo6MM6o',
      'oo66oooo66oo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'o.oo.oo.oo.o',
      '...o....o...',
      '............',
      '77.77..77.77',
      '.77.7777.77.',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'reactor',
    name: 'REACTOR',
    rows: [
      '............',
      '............',
      '............',
      '............',
      '....oooo....',
      '...o9999o...',
      '..o999999o..',
      '..o999999o..',
      '.o99MMMM99o.',
      '.o99MMMM99o.',
      '.o9MMMMMM9o.',
      '.99MMMMMM99.',
      '.99MMMMMM99.',
      '.99MMMMMM99.',
      '.99MMMMMM99.',
      '.o9MMMMMM9o.',
      '.o99MMMM99o.',
      '.o99MMMM99o.',
      '..o999999o..',
      '..o999999o..',
      '...o9999o...',
      '....oooo....',
      '............',
      '............',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'crown',
    name: 'CROWN',
    rows: [
      '............',
      '............',
      '............',
      'M....MM....M',
      'o....oo....o',
      'oo..oooo..oo',
      'o8..8oo8..8o',
      'oo88oooo88oo',
      'oooMooooMooo',
      'ooo8oooo8ooo',
      '8oooooooooo8',
      '888888888888',
      '7o7o7oo7o7o7',
      '777777777777',
      '............',
      '............',
      'o5oo5oo5oo5o',
      'o5oo5oo5oo5o',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'keyhole',
    name: 'KEYHOLE',
    rows: [
      '............',
      '777777777777',
      '777777777777',
      '777777777777',
      '7777XXXX7777',
      '777XMMMMX777',
      '777XMMMMX777',
      '7777X..X7777',
      '7777X..X7777',
      '7777X..X7777',
      '7777X..X7777',
      '7777X..X7777',
      '777777777777',
      '777777777777',
      '777777777777',
      '............',
      'o5oo5oo5oo5o',
      'o5oo5oo5oo5o',
      'o5oo5oo5oo5o',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'domino',
    name: 'DOMINO',
    rows: [
      '............',
      '............',
      'Mo.oo.oM.Mo.',
      'oo.oM.Mo.oo.',
      '66.66.66.66.',
      'Mo.oo.oM.Mo.',
      '............',
      'Mo.oo.oM.Mo.',
      'oo.oM.Mo.oo.',
      '66.66.66.66.',
      'Mo.oo.oM.Mo.',
      '............',
      'Mo.oo.oM.Mo.',
      'oo.oM.Mo.oo.',
      '66.66.66.66.',
      'Mo.oo.oM.Mo.',
      '............',
      'Mo.oo.oM.Mo.',
      'oo.oM.Mo.oo.',
      '66.66.66.66.',
      'Mo.oo.oM.Mo.',
      '............',
      'Mo.oo.oM.Mo.',
      'oo.oM.Mo.oo.',
      '66.66.66.66.',
      'Mo.oo.oM.Mo.',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'serpent',
    name: 'SERPENT',
    rows: [
      '............',
      '............',
      'oo77777777oo',
      'o7oooooooo7o',
      'o7ooMooooo7o',
      'o77777777o7o',
      'ooooooooo.7o',
      'o77777777o7o',
      'o7ooooooooo.',
      'o7oooMoooo7o',
      'o7o77777777o',
      'o.ooooooooo.',
      'o7o77777777o',
      'o7ooooooooo.',
      'o7oooooMoo7o',
      'o77777777o7o',
      'oooooooooo7o',
      'oo77777777oo',
      '............',
      'o4oo4oo4oo4o',
      'o4oo4oo4oo4o',
      'o4oo4oo4oo4o',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'pachinko',
    name: 'PACHINKO',
    rows: [
      'XoXoXoXoXoXo',
      'oooooooooooo',
      'oXoXoXoXoXoX',
      'oooooooooooo',
      'XoXoXoXoXoXo',
      'oooooooooooo',
      'oXoXoXoXoXoX',
      'oooooooooooo',
      'XoXoXoXoXoXo',
      'oooooooooooo',
      'oXoXoXoXoXoX',
      'oooooooooooo',
      'XoXoXoXoXoXo',
      'oooooooooooo',
      'oXoXoXoXoXoX',
      'oooooooooooo',
      'XoXoXoXoXoXo',
      'oooooooooooo',
      'oXoXoXoXoXoX',
      'oooooooooooo',
      'XoXoXoXoXoXo',
      'oooooooooooo',
      'oXoXoXoXoXoX',
      'oooooooooooo',
      'XoXoXoXoXoXo',
      'oooooooooooo',
      'oXoXoXoXoXoX',
      'oooooooooooo',
      'XoXoXoXoXoXo',
      'oooooooooooo',
    ],
  },
  {
    id: 'vortex',
    name: 'VORTEX',
    rows: [
      '............',
      '............',
      '8ooooo.....7',
      '8ooooo.....7',
      '.8oooo....75',
      '.8oooo....75',
      '..8ooo...755',
      '..8ooo...755',
      '...8oo..7555',
      '...8oo..7555',
      '....8o.75555',
      '....8o.75555',
      '.....MM55555',
      '.....MM55555',
      '55555MM.....',
      '55555MM.....',
      '55557.o8....',
      '55557.o8....',
      '5557..oo8...',
      '5557..oo8...',
      '557...ooo8..',
      '557...ooo8..',
      '57....oooo8.',
      '57....oooo8.',
      '7.....ooooo8',
      '7.....ooooo8',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'anchor',
    name: 'ANCHOR',
    rows: [
      '............',
      '....7777....',
      '...7o77o7...',
      '....7777....',
      '..77777777..',
      '.....77.....',
      '.....77.....',
      '.....77.....',
      '.....77.....',
      '.....77.....',
      '.7...77...7.',
      '77...77...77',
      '.77..77..77.',
      '..77.77.77..',
      '...777777...',
      '............',
      '............',
      'oMooooooooMo',
      'oMooooooooMo',
      'oMooooooooMo',
      'oMooooooooMo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'cathedral',
    name: 'CATHEDRAL',
    rows: [
      '.....88.....',
      '....8888....',
      '....8MM8....',
      '...8oooo8...',
      '...8oooo8...',
      '..88888888..',
      '..7oo77oo7..',
      '..7o7oo7o7..',
      '.77oo77oo77.',
      '.7oo7oo7oo7.',
      '77oMo77oMo77',
      '7o7oo77oo7o7',
      '7oo7oooo7oo7',
      '7o7oooooo7o7',
      '777777777777',
      '............',
      'o7ooo55ooo7o',
      'o7ooo55ooo7o',
      'o7ooo55ooo7o',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'planet',
    name: 'PLANET',
    rows: [
      '............',
      'o...........',
      '......o.....',
      '............',
      '............',
      '.o...oo.....',
      '....ooo5....',
      '...ooo5oo...',
      '...oo5ooo..7',
      '..oo588o5777',
      '...5o88MM7..',
      '..5o8MM8oo..',
      '..7MM88oo...',
      '777o588o5...',
      '7..5ooo5oo..',
      '...ooo5oo...',
      '....o5oo....',
      '....ooo.....',
      '..........o.',
      '............',
      '............',
      '.....o......',
      '...........o',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'avalanche',
    name: 'AVALANCHE',
    rows: [
      '............',
      '............',
      '999999999999',
      '999999999999',
      '999999999999',
      '999999999999',
      '888888888888',
      '888M8888M888',
      '888888888888',
      '888888888888',
      '777777777777',
      '777777777777',
      '777777777777',
      '777777777777',
      '666666666666',
      '6M666MM666M6',
      '666666666666',
      '555555555555',
      '555555555555',
      '555555555555',
      '444444444444',
      '444444444444',
      '444444444444',
      '33M333333M33',
      '333333333333',
      '333333333333',
      '222222222222',
      '222222222222',
      '222222222222',
      '222222222222',
    ],
  },
  {
    id: 'mosaic',
    name: 'MOSAIC',
    rows: [
      '............',
      '............',
      'oooooooo3355',
      'oooooooo3355',
      '7744oooooooo',
      '7744oooooooo',
      '..6ooo..6ooo',
      '..6ooo..6ooo',
      '55M4oo55M4oo',
      '55M4oo55M4oo',
      'oo3oooooo744',
      'oo3oooooo744',
      'ooo4oo774.66',
      'ooo4oo774.66',
      '44oooo335M..',
      '44oooo335M..',
      '6674ooooo355',
      '6674ooooo355',
      'MM.ooo667o33',
      'MM.ooo667o33',
      '3354ooMM.ooo',
      '3354ooMM.ooo',
      'oooooooooooo',
      'oooooooooooo',
      'ooo4oo44o744',
      'ooo4oo44o744',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'bastion',
    name: 'BASTION',
    rows: [
      '............',
      'X.XX.XX.XX.X',
      'X7777777777X',
      'X7MM7777MM7X',
      'X7MM7777MM7X',
      'X7777777777X',
      'XXX.XXXX.XXX',
      '.o888oo888o.',
      '.o8M8oo8M8o.',
      '.o888oo888o.',
      '.oooooooooo.',
      'X.XXXXXXXX.X',
      'o6o6o66o6o6o',
      '666666666666',
      'o6o6o66o6o6o',
      'XXXX.XX.XXXX',
      '............',
      'oo5oo55oo5oo',
      'oo5oo55oo5oo',
      'oo5oo55oo5oo',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'eclipse',
    name: 'ECLIPSE',
    rows: [
      '............',
      '............',
      '.....oo.....',
      '...oooooo...',
      '...oo66oo...',
      '..oo6688oo..',
      '.oo668888oo.',
      '.o66688888o.',
      '.o66888888o.',
      'oo66888888oo',
      'o6668MM8888o',
      'o666MMMM888o',
      'o666MMMM888o',
      'o666MMMM888o',
      'o666MMMM888o',
      'o6668MM8886o',
      'oo66688888oo',
      '.o66688886o.',
      '.o66666866o.',
      '.oo666666oo.',
      '..oo6666oo..',
      '...oo66oo...',
      '...oooooo...',
      '.....oo.....',
      '............',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'gauntlet',
    name: 'GAUNTLET',
    rows: [
      'oooooooooooo',
      'XXXXXXXXXX.X',
      'o8o8o8o8o8oo',
      'oo7oo7oo7oo7',
      'X.XXXXXXXXXX',
      'oo8oo8oo8oo8',
      'o7o7oMo7o7oo',
      'XXXXXXXX.XXX',
      'o6o6o6o6o6o6',
      '6o6oMo6o6o6o',
      'XX.XXXXXXXXX',
      'o8oo8oo8oo8o',
      '77o77o77M77o',
      'XXXXX.XXXXXX',
      'o6o6o6o6o6o6',
      '6o6o6o6o6oMo',
      'XXXXXXXXXX.X',
      '............',
      'o5oo5oo5oo5o',
      'o5oo5oo5oo5o',
      'o5oo5oo5oo5o',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'omega',
    name: 'OMEGA',
    rows: [
      '999999999999',
      '9MMMMMMMMMM9',
      '9MMMMMMMMMM9',
      '999999999999',
      'X9999XX9999X',
      'X8888888888X',
      'X8MM8888MM8X',
      'X8888888888X',
      'X.XXXXXXXX.X',
      '888888888888',
      '8MM888888MM8',
      '888888888888',
      'XXXX.XX.XXXX',
      '777777777777',
      '7MM77MM77MM7',
      '777777777777',
      'X.XXXXXXXX.X',
      '666666666666',
      '6M66666666M6',
      '666666666666',
      'XXXX.XX.XXXX',
      '9o9o9oo9o9o9',
      'o9o9o99o9o9o',
      '............',
      'o6oo6oo6oo6o',
      'o6oo6oo6oo6o',
      'o6oo6oo6oo6o',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
]);
