import { parseStage } from '../sim/stage-parse.ts';
import type { StageDef } from '../sim/stage-parse.ts';

/** 読み込み時にすべてのステージを検証する。配置の誤りや id の重複は、起動した時点でエラーにする */
function defineStages(defs: readonly StageDef[]): readonly StageDef[] {
  const ids = new Set<string>();
  for (const def of defs) {
    parseStage(def);
    if (ids.has(def.id)) throw new Error(`stage id "${def.id}" is used more than once`);
    ids.add(def.id);
  }
  return defs;
}

export const STAGES: readonly StageDef[] = defineStages([
  {
    id: 'ignition',
    name: 'IGNITION',
    rows: [
      '............',
      '............',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'ooooooMooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'ooMooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      '333333333333',
      '............',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'floodgate',
    name: 'FLOODGATE',
    rows: [
      '............',
      '............',
      '............',
      'oooooooooooo',
      'ooMooooooMoo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'ooooooMooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
      '55555o555555',
      '555555555555',
      '............',
      'o3o3o3o3o3o3',
      '3o3o3o3o3o3o',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'circuit',
    name: 'CIRCUIT',
    rows: [
      '............',
      '............',
      '............',
      'oMoooMoooMoo',
      'oooooooooooo',
      '%%%%%%%%%%%.',
      'oooooooooooo',
      'ooMoooMoooMo',
      '.%%%%%%%%%%%',
      'oooooooooooo',
      'oooooooooooo',
      '%%%%%.%%%%%%',
      'oooMoooMoooo',
      'oooooooooooo',
      'o6oo6oo6oo6o',
      'oooooooooooo',
      '6oo6oo6oo6oo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'prism',
    name: 'PRISM',
    rows: [
      '............',
      '............',
      '............',
      '.....##.....',
      '....#MM#....',
      '...#oMMo#...',
      '..#oooooo#..',
      '.#oooMMooo#.',
      '#oooMooMooo#',
      '.#oooMMooo#.',
      '..#oooooo#..',
      '...#oooo#...',
      '....#oo#....',
      '.....##.....',
      '............',
      'o4oo4oo4oo4o',
      'oooooooooooo',
      '4oo4oo4oo4oo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
  {
    id: 'fortress',
    name: 'FORTRESS',
    rows: [
      '............',
      '............',
      '............',
      '############',
      '#9999999999#',
      '#9MMMMMMMM9#',
      '#9MMMMMMMM9#',
      '#9999999999#',
      '#####oo#####',
      'ooooMooMoooo',
      'oooooooooooo',
      '6o6o6o6o6o6o',
      'oooooooooooo',
      'o6o6o6o6o6o6',
      'oooooooooooo',
      '##oooooooo##',
      'ooooMooMoooo',
      'oooooooooooo',
      'oooooooooooo',
      'oooooooooooo',
    ],
  },
]);
